---
deployment:
  tasks:
    - export REPO=$HOME/repositories/tokonesia
    - export DEPLOYPATH=$HOME/tokonesia.corefive.my.id

    # 1) Tarik commit terbaru ke repo lokal cPanel
    - cd "$REPO" && git fetch -q origin main && git reset -q --hard origin/main

    # 2) Salin semua file ke direktori website
    - cd "$REPO" && /bin/tar -cf - --exclude='.git' --exclude='.github' --exclude='.cpanel.yml' --exclude='.gitignore' --exclude='.gitattributes' . | ( cd "$DEPLOYPATH" && /bin/tar -xf - --no-overwrite-dir --no-same-permissions )

    # 3) Kunci permission folder website
    - /bin/chmod 750 "$DEPLOYPATH"

    # 4) Jalankan script migrasi otomatis & catat ke migration.log
    - /bin/bash "$DEPLOYPATH/deploy_migrate.sh"
